### ISSUE TITLE
add `angel` to the list of devops tools

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/commercialhaskell#77]
Would it be appropriate to add something like [angel](https://github.com/MichaelXavier/Angel) to the list of devops tools?  I guess it's more operations than development, so it may not be appropriate for that list.

It's a replacement for daemontools, supervisord, etc.

Maybe @MichaelXavier would like to comment on this?

At my current company [ARoW Co., Ltd.](http://www.arow.info), we're using angel in production, and it is working nicely.

**Comment by snoyberg** [comment]
Definitely! I just invited you to be a contributor to this repo, please go ahead with adding it to the list of tools.

**Comment by cdepillabout** [comment]
Thanks!  I added a link to `angel`!

**Comment by ericfode** [comment]
@cdepillabout Thanks for adding this!
